name: Build Windows (x86, x64) Tests

on:
  push:
    branches-ignore:
      - master
  workflow_dispatch:
    inputs:
      update-caches:
        description: "Whether to update the `ccache` or `bazel` caches, where possible."
        default: false
        required: false
        type: boolean

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}
          max-size: "500M"
          save: ${{ github.event_name == 'workflow_dispatch' && inputs.update-caches || 'false' }}
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Setup build environment
        shell: bash
        run: |
          echo "VCVARSALL=$(vswhere -products \* -latest -property installationPath)\\VC\\Auxiliary\\Build\\vcvarsall.bat" >> $GITHUB_ENV
      - name: Configure and build
        run: scripts/build-windows-x64.cmd
        shell: cmd
        working-directory: ${{ github.workspace }}
        env:
          CFLAGS: "/UNDEBUG"
          CXXFLAGS: "/UNDEBUG"
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/windows/x64/      

  sde-test:
    uses: ./.github/workflows/sde-test.yml
