name: Test SDE 

on:
  push:
    branches-ignore:
      - master
  workflow_dispatch:

jobs:
  build-run-sde-all:
    uses: ./.github/workflows/run-sde_all.yml
    with:
      instruction-set: ALL
    if: ${{ inputs.instruction-set == 'ALL' }}
