name: Test Latest Push in Intel SDE

on:
  workflow_dispatch:
    inputs:
      run-tests:
        description: "Whether to also run unit tests where possible."
        default: true
        required: false
        type: boolean
      update-caches:
        description: "Whether to update the `ccache` or `bazel` caches, where possible."
        default: false
        required: false
        type: boolean
      sde-processor:
        description: "Pick a SDE Processor to run tests"
        required: true
        default: "Skylake" # Optionally set a default value

jobs:
  build-and-test-sde-skl:
    runs-on: windows-latest
    if: ${{ inputs.sde-processor == 'Skylake' || inputs.sde-processor == 'ALL' }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}
          max-size: "500M"
          save: ${{ inputs.update-caches }}
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Setup build environment
        shell: bash
        run: |
          echo "VCVARSALL=$(vswhere -products \* -latest -property installationPath)\\VC\\Auxiliary\\Build\\vcvarsall.bat" >> $GITHUB_ENV
      - name: Configure and build
        run: scripts/build-windows-x64.cmd
        shell: cmd
        working-directory: ${{ github.workspace }}
        env:
          CFLAGS: "/UNDEBUG"
          CXXFLAGS: "/UNDEBUG"
      - name: Download Intel SDE using curl
        run: |
          curl -L -o sde-external-9.44.0-2024-08-22-win.tar.xz https://downloadmirror.intel.com/831748/sde-external-9.44.0-2024-08-22-win.tar.xz
      - name: Extract Intel SDE
        shell: bash
        run: |
          tar -xf sde-external-9.44.0-2024-08-22-win.tar.xz
      - name: Run tests using Intel SDE Skylake Processor
        if: ${{ inputs.run-tests }}
        run: |
          ${{ github.workspace }}\sde-external-9.44.0-2024-08-22-win\sde.exe -skl -- ctest -C Release --parallel $Env:NUMBER_OF_PROCESSORS
        working-directory: ${{ github.workspace }}/build/windows/x64

  build-and-test-sde-cnl:
    runs-on: windows-latest
    if: ${{ inputs.sde-processor == 'Cannon_Lake' || inputs.sde-processor == 'ALL' }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}
          max-size: "500M"
          save: ${{ inputs.update-caches }}
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Setup build environment
        shell: bash
        run: |
          echo "VCVARSALL=$(vswhere -products \* -latest -property installationPath)\\VC\\Auxiliary\\Build\\vcvarsall.bat" >> $GITHUB_ENV
      - name: Configure and build
        run: scripts/build-windows-x64.cmd
        shell: cmd
        working-directory: ${{ github.workspace }}
        env:
          CFLAGS: "/UNDEBUG"
          CXXFLAGS: "/UNDEBUG"
      - name: Download Intel SDE using curl
        run: |
          curl -L -o sde-external-9.44.0-2024-08-22-win.tar.xz https://downloadmirror.intel.com/831748/sde-external-9.44.0-2024-08-22-win.tar.xz
      - name: Extract Intel SDE
        shell: bash
        run: |
          tar -xf sde-external-9.44.0-2024-08-22-win.tar.xz
      - name: Run tests using Intel SDE Cannon_Lake Processor
        if: ${{ inputs.run-tests }}
        run: |
          ${{ github.workspace }}\sde-external-9.44.0-2024-08-22-win\sde.exe -cnl -- ctest -C Release --parallel $Env:NUMBER_OF_PROCESSORS
        working-directory: ${{ github.workspace }}/build/windows/x64

  build-and-test-sde-icl:
    runs-on: windows-latest
    if: ${{ inputs.sde-processor == 'Ice_Lake' || inputs.sde-processor == 'ALL' }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}
          max-size: "500M"
          save: ${{ inputs.update-caches }}
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Setup build environment
        shell: bash
        run: |
          echo "VCVARSALL=$(vswhere -products \* -latest -property installationPath)\\VC\\Auxiliary\\Build\\vcvarsall.bat" >> $GITHUB_ENV
      - name: Configure and build
        run: scripts/build-windows-x64.cmd
        shell: cmd
        working-directory: ${{ github.workspace }}
        env:
          CFLAGS: "/UNDEBUG"
          CXXFLAGS: "/UNDEBUG"
      - name: Download Intel SDE using curl
        run: |
          curl -L -o sde-external-9.44.0-2024-08-22-win.tar.xz https://downloadmirror.intel.com/831748/sde-external-9.44.0-2024-08-22-win.tar.xz
      - name: Extract Intel SDE
        shell: bash
        run: |
          tar -xf sde-external-9.44.0-2024-08-22-win.tar.xz
      - name: Run tests using Intel SDE Ice_Lake Processor
        if: ${{ inputs.run-tests }}
        run: |
          ${{ github.workspace }}\sde-external-9.44.0-2024-08-22-win\sde.exe -icl -- ctest -C Release --parallel $Env:NUMBER_OF_PROCESSORS
        working-directory: ${{ github.workspace }}/build/windows/x64

  build-and-test-sde-skx:
    runs-on: windows-latest
    if: ${{ inputs.sde-processor == 'Skylake_server' || inputs.sde-processor == 'ALL' }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}
          max-size: "500M"
          save: ${{ inputs.update-caches }}
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Setup build environment
        shell: bash
        run: |
          echo "VCVARSALL=$(vswhere -products \* -latest -property installationPath)\\VC\\Auxiliary\\Build\\vcvarsall.bat" >> $GITHUB_ENV
      - name: Configure and build
        run: scripts/build-windows-x64.cmd
        shell: cmd
        working-directory: ${{ github.workspace }}
        env:
          CFLAGS: "/UNDEBUG"
          CXXFLAGS: "/UNDEBUG"
      - name: Download Intel SDE using curl
        run: |
          curl -L -o sde-external-9.44.0-2024-08-22-win.tar.xz https://downloadmirror.intel.com/831748/sde-external-9.44.0-2024-08-22-win.tar.xz
      - name: Extract Intel SDE
        shell: bash
        run: |
          tar -xf sde-external-9.44.0-2024-08-22-win.tar.xz
      - name: Run tests using Intel SDE Skylake_server Processor
        if: ${{ inputs.run-tests }}
        run: |
          ${{ github.workspace }}\sde-external-9.44.0-2024-08-22-win\sde.exe -skx -- ctest -C Release --parallel $Env:NUMBER_OF_PROCESSORS
        working-directory: ${{ github.workspace }}/build/windows/x64

  build-and-test-sde-clx:
    runs-on: windows-latest
    if: ${{ inputs.sde-processor == 'Cascade_Lake ' || inputs.sde-processor == 'ALL' }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}
          max-size: "500M"
          save: ${{ inputs.update-caches }}
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Setup build environment
        shell: bash
        run: |
          echo "VCVARSALL=$(vswhere -products \* -latest -property installationPath)\\VC\\Auxiliary\\Build\\vcvarsall.bat" >> $GITHUB_ENV
      - name: Configure and build
        run: scripts/build-windows-x64.cmd
        shell: cmd
        working-directory: ${{ github.workspace }}
        env:
          CFLAGS: "/UNDEBUG"
          CXXFLAGS: "/UNDEBUG"
      - name: Download Intel SDE using curl
        run: |
          curl -L -o sde-external-9.44.0-2024-08-22-win.tar.xz https://downloadmirror.intel.com/831748/sde-external-9.44.0-2024-08-22-win.tar.xz
      - name: Extract Intel SDE
        shell: bash
        run: |
          tar -xf sde-external-9.44.0-2024-08-22-win.tar.xz
      - name: Run tests using Intel SDE Cascade_Lake Processor
        if: ${{ inputs.run-tests }}
        run: |
          ${{ github.workspace }}\sde-external-9.44.0-2024-08-22-win\sde.exe -clx -- ctest -C Release --parallel $Env:NUMBER_OF_PROCESSORS
        working-directory: ${{ github.workspace }}/build/windows/x64

  build-and-test-sde-cpx:
    runs-on: windows-latest
    if: ${{ inputs.sde-processor == 'Cooper_Lake' || inputs.sde-processor == 'ALL' }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}
          max-size: "500M"
          save: ${{ inputs.update-caches }}
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Setup build environment
        shell: bash
        run: |
          echo "VCVARSALL=$(vswhere -products \* -latest -property installationPath)\\VC\\Auxiliary\\Build\\vcvarsall.bat" >> $GITHUB_ENV
      - name: Configure and build
        run: scripts/build-windows-x64.cmd
        shell: cmd
        working-directory: ${{ github.workspace }}
        env:
          CFLAGS: "/UNDEBUG"
          CXXFLAGS: "/UNDEBUG"
      - name: Download Intel SDE using curl
        run: |
          curl -L -o sde-external-9.44.0-2024-08-22-win.tar.xz https://downloadmirror.intel.com/831748/sde-external-9.44.0-2024-08-22-win.tar.xz
      - name: Extract Intel SDE
        shell: bash
        run: |
          tar -xf sde-external-9.44.0-2024-08-22-win.tar.xz
      - name: Run tests using Intel SDE Cooper_Lake Processor
        if: ${{ inputs.run-tests }}
        run: |
          ${{ github.workspace }}\sde-external-9.44.0-2024-08-22-win\sde.exe -cpx -- ctest -C Release --parallel $Env:NUMBER_OF_PROCESSORS
        working-directory: ${{ github.workspace }}/build/windows/x64

  build-and-test-sde-icx:
    runs-on: windows-latest
    if: ${{ inputs.sde-processor == 'Ice_Lake_server' || inputs.sde-processor == 'ALL' }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}
          max-size: "500M"
          save: ${{ inputs.update-caches }}
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Setup build environment
        shell: bash
        run: |
          echo "VCVARSALL=$(vswhere -products \* -latest -property installationPath)\\VC\\Auxiliary\\Build\\vcvarsall.bat" >> $GITHUB_ENV
      - name: Configure and build
        run: scripts/build-windows-x64.cmd
        shell: cmd
        working-directory: ${{ github.workspace }}
        env:
          CFLAGS: "/UNDEBUG"
          CXXFLAGS: "/UNDEBUG"
      - name: Download Intel SDE using curl
        run: |
          curl -L -o sde-external-9.44.0-2024-08-22-win.tar.xz https://downloadmirror.intel.com/831748/sde-external-9.44.0-2024-08-22-win.tar.xz
      - name: Extract Intel SDE
        shell: bash
        run: |
          tar -xf sde-external-9.44.0-2024-08-22-win.tar.xz
      - name: Run tests using Intel SDE Ice_Lake_server Processor
        if: ${{ inputs.run-tests }}
        run: |
          ${{ github.workspace }}\sde-external-9.44.0-2024-08-22-win\sde.exe -icx -- ctest -C Release --parallel $Env:NUMBER_OF_PROCESSORS
        working-directory: ${{ github.workspace }}/build/windows/x64

  build-and-test-sde-tgl:
    runs-on: windows-latest
    if: ${{ inputs.sde-processor == 'Tiger_Lake' || inputs.sde-processor == 'ALL' }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}
          max-size: "500M"
          save: ${{ inputs.update-caches }}
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Setup build environment
        shell: bash
        run: |
          echo "VCVARSALL=$(vswhere -products \* -latest -property installationPath)\\VC\\Auxiliary\\Build\\vcvarsall.bat" >> $GITHUB_ENV
      - name: Configure and build
        run: scripts/build-windows-x64.cmd
        shell: cmd
        working-directory: ${{ github.workspace }}
        env:
          CFLAGS: "/UNDEBUG"
          CXXFLAGS: "/UNDEBUG"
      - name: Download Intel SDE using curl
        run: |
          curl -L -o sde-external-9.44.0-2024-08-22-win.tar.xz https://downloadmirror.intel.com/831748/sde-external-9.44.0-2024-08-22-win.tar.xz
      - name: Extract Intel SDE
        shell: bash
        run: |
          tar -xf sde-external-9.44.0-2024-08-22-win.tar.xz
      - name: Run tests using Intel SDE Tiger_Lake Processor
        if: ${{ inputs.run-tests }}
        run: |
          ${{ github.workspace }}\sde-external-9.44.0-2024-08-22-win\sde.exe -tgl -- ctest -C Release --parallel $Env:NUMBER_OF_PROCESSORS
        working-directory: ${{ github.workspace }}/build/windows/x64

  build-and-test-sde-adl:
    runs-on: windows-latest
    if: ${{ inputs.sde-processor == 'Alder_Lake' || inputs.sde-processor == 'ALL' }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}
          max-size: "500M"
          save: ${{ inputs.update-caches }}
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Setup build environment
        shell: bash
        run: |
          echo "VCVARSALL=$(vswhere -products \* -latest -property installationPath)\\VC\\Auxiliary\\Build\\vcvarsall.bat" >> $GITHUB_ENV
      - name: Configure and build
        run: scripts/build-windows-x64.cmd
        shell: cmd
        working-directory: ${{ github.workspace }}
        env:
          CFLAGS: "/UNDEBUG"
          CXXFLAGS: "/UNDEBUG"
      - name: Download Intel SDE using curl
        run: |
          curl -L -o sde-external-9.44.0-2024-08-22-win.tar.xz https://downloadmirror.intel.com/831748/sde-external-9.44.0-2024-08-22-win.tar.xz
      - name: Extract Intel SDE
        shell: bash
        run: |
          tar -xf sde-external-9.44.0-2024-08-22-win.tar.xz
      - name: Run tests using Intel SDE Alder_Lake Processor
        if: ${{ inputs.run-tests }}
        run: |
          ${{ github.workspace }}\sde-external-9.44.0-2024-08-22-win\sde.exe -adl -- ctest -C Release --parallel $Env:NUMBER_OF_PROCESSORS
        working-directory: ${{ github.workspace }}/build/windows/x64

  build-and-test-sde-mtl:
    runs-on: windows-latest
    if: ${{ inputs.sde-processor == 'Meteor_Lake' || inputs.sde-processor == 'ALL' }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}
          max-size: "500M"
          save: ${{ inputs.update-caches }}
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Setup build environment
        shell: bash
        run: |
          echo "VCVARSALL=$(vswhere -products \* -latest -property installationPath)\\VC\\Auxiliary\\Build\\vcvarsall.bat" >> $GITHUB_ENV
      - name: Configure and build
        run: scripts/build-windows-x64.cmd
        shell: cmd
        working-directory: ${{ github.workspace }}
        env:
          CFLAGS: "/UNDEBUG"
          CXXFLAGS: "/UNDEBUG"
      - name: Download Intel SDE using curl
        run: |
          curl -L -o sde-external-9.44.0-2024-08-22-win.tar.xz https://downloadmirror.intel.com/831748/sde-external-9.44.0-2024-08-22-win.tar.xz
      - name: Extract Intel SDE
        shell: bash
        run: |
          tar -xf sde-external-9.44.0-2024-08-22-win.tar.xz
      - name: Run tests using Intel SDE Meteor_Lake Processor
        if: ${{ inputs.run-tests }}
        run: |
          ${{ github.workspace }}\sde-external-9.44.0-2024-08-22-win\sde.exe -mtl -- ctest -C Release --parallel $Env:NUMBER_OF_PROCESSORS
        working-directory: ${{ github.workspace }}/build/windows/x64

  build-and-test-sde-rpl:
    runs-on: windows-latest
    if: ${{ inputs.sde-processor == 'Raptor_Lake' || inputs.sde-processor == 'ALL' }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}
          max-size: "500M"
          save: ${{ inputs.update-caches }}
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Setup build environment
        shell: bash
        run: |
          echo "VCVARSALL=$(vswhere -products \* -latest -property installationPath)\\VC\\Auxiliary\\Build\\vcvarsall.bat" >> $GITHUB_ENV
      - name: Configure and build
        run: scripts/build-windows-x64.cmd
        shell: cmd
        working-directory: ${{ github.workspace }}
        env:
          CFLAGS: "/UNDEBUG"
          CXXFLAGS: "/UNDEBUG"
      - name: Download Intel SDE using curl
        run: |
          curl -L -o sde-external-9.44.0-2024-08-22-win.tar.xz https://downloadmirror.intel.com/831748/sde-external-9.44.0-2024-08-22-win.tar.xz
      - name: Extract Intel SDE
        shell: bash
        run: |
          tar -xf sde-external-9.44.0-2024-08-22-win.tar.xz
      - name: Run tests using Intel SDE Raptor_Lake Processor
        if: ${{ inputs.run-tests }}
        run: |
          ${{ github.workspace }}\sde-external-9.44.0-2024-08-22-win\sde.exe -rpl -- ctest -C Release --parallel $Env:NUMBER_OF_PROCESSORS
        working-directory: ${{ github.workspace }}/build/windows/x64

  build-and-test-sde-spr:
    runs-on: windows-latest
    if: ${{ inputs.sde-processor == 'Sapphire_Rapids' || inputs.sde-processor == 'ALL' }}
    #timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}
          max-size: "500M"
          save: ${{ inputs.update-caches }}
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Setup build environment
        shell: bash
        run: |
          echo "VCVARSALL=$(vswhere -products \* -latest -property installationPath)\\VC\\Auxiliary\\Build\\vcvarsall.bat" >> $GITHUB_ENV
      - name: Configure and build
        run: scripts/build-windows-x64.cmd
        shell: cmd
        working-directory: ${{ github.workspace }}
        env:
          CFLAGS: "/UNDEBUG"
          CXXFLAGS: "/UNDEBUG"
      - name: Download Intel SDE using curl
        run: |
          curl -L -o sde-external-9.44.0-2024-08-22-win.tar.xz https://downloadmirror.intel.com/831748/sde-external-9.44.0-2024-08-22-win.tar.xz
      - name: Extract Intel SDE
        shell: bash
        run: |
          tar -xf sde-external-9.44.0-2024-08-22-win.tar.xz
      - name: Run tests using Intel SDE Sapphire_Rapids Processor
        if: ${{ inputs.run-tests }}
        run: |
          ${{ github.workspace }}\sde-external-9.44.0-2024-08-22-win\sde.exe -spr -- ctest -C Release --parallel $Env:NUMBER_OF_PROCESSORS
        working-directory: ${{ github.workspace }}/build/windows/x64

  build-and-test-sde-emr:
    runs-on: windows-latest
    if: ${{ inputs.sde-processor == 'Emerald_Rapids' || inputs.sde-processor == 'ALL' }}
    #timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}
          max-size: "500M"
          save: ${{ inputs.update-caches }}
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Setup build environment
        shell: bash
        run: |
          echo "VCVARSALL=$(vswhere -products \* -latest -property installationPath)\\VC\\Auxiliary\\Build\\vcvarsall.bat" >> $GITHUB_ENV
      - name: Configure and build
        run: scripts/build-windows-x64.cmd
        shell: cmd
        working-directory: ${{ github.workspace }}
        env:
          CFLAGS: "/UNDEBUG"
          CXXFLAGS: "/UNDEBUG"
      - name: Download Intel SDE using curl
        run: |
          curl -L -o sde-external-9.44.0-2024-08-22-win.tar.xz https://downloadmirror.intel.com/831748/sde-external-9.44.0-2024-08-22-win.tar.xz
      - name: Extract Intel SDE
        shell: bash
        run: |
          tar -xf sde-external-9.44.0-2024-08-22-win.tar.xz
      - name: Run tests using Intel SDE Emerald_Rapids Processor
        if: ${{ inputs.run-tests }}
        run: |
          ${{ github.workspace }}\sde-external-9.44.0-2024-08-22-win\sde.exe -emr -- ctest -C Release --parallel $Env:NUMBER_OF_PROCESSORS
        working-directory: ${{ github.workspace }}/build/windows/x64

  build-and-test-sde-gnr:
    runs-on: windows-latest
    if: ${{ inputs.sde-processor == 'Granite_Rapids' || inputs.sde-processor == 'ALL' }}
    #timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}
          max-size: "500M"
          save: ${{ inputs.update-caches }}
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Setup build environment
        shell: bash
        run: |
          echo "VCVARSALL=$(vswhere -products \* -latest -property installationPath)\\VC\\Auxiliary\\Build\\vcvarsall.bat" >> $GITHUB_ENV
      - name: Configure and build
        run: scripts/build-windows-x64.cmd
        shell: cmd
        working-directory: ${{ github.workspace }}
        env:
          CFLAGS: "/UNDEBUG"
          CXXFLAGS: "/UNDEBUG"
      - name: Download Intel SDE using curl
        run: |
          curl -L -o sde-external-9.44.0-2024-08-22-win.tar.xz https://downloadmirror.intel.com/831748/sde-external-9.44.0-2024-08-22-win.tar.xz
      - name: Extract Intel SDE
        shell: bash
        run: |
          tar -xf sde-external-9.44.0-2024-08-22-win.tar.xz
      - name: Run tests using Intel SDE Granite_Rapids Processor
        if: ${{ inputs.run-tests }}
        run: |
          ${{ github.workspace }}\sde-external-9.44.0-2024-08-22-win\sde.exe -gnr -- ctest -C Release --parallel $Env:NUMBER_OF_PROCESSORS
        working-directory: ${{ github.workspace }}/build/windows/x64

  build-and-test-sde-srf:
    runs-on: windows-latest
    if: ${{ inputs.sde-processor == 'Sierra_Forest' || inputs.sde-processor == 'ALL' }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}
          max-size: "500M"
          save: ${{ inputs.update-caches }}
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Setup build environment
        shell: bash
        run: |
          echo "VCVARSALL=$(vswhere -products \* -latest -property installationPath)\\VC\\Auxiliary\\Build\\vcvarsall.bat" >> $GITHUB_ENV
      - name: Configure and build
        run: scripts/build-windows-x64.cmd
        shell: cmd
        working-directory: ${{ github.workspace }}
        env:
          CFLAGS: "/UNDEBUG"
          CXXFLAGS: "/UNDEBUG"
      - name: Download Intel SDE using curl
        run: |
          curl -L -o sde-external-9.44.0-2024-08-22-win.tar.xz https://downloadmirror.intel.com/831748/sde-external-9.44.0-2024-08-22-win.tar.xz
      - name: Extract Intel SDE
        shell: bash
        run: |
          tar -xf sde-external-9.44.0-2024-08-22-win.tar.xz
      - name: Run tests using Intel SDE Sierra_Forest Processor
        if: ${{ inputs.run-tests }}
        run: |
          ${{ github.workspace }}\sde-external-9.44.0-2024-08-22-win\sde.exe -srf -- ctest -C Release --parallel $Env:NUMBER_OF_PROCESSORS
        working-directory: ${{ github.workspace }}/build/windows/x64

  build-and-test-sde-arl:
    runs-on: windows-latest
    if: ${{ inputs.sde-processor == 'Arrow_Lake' || inputs.sde-processor == 'ALL' }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}
          max-size: "500M"
          save: ${{ inputs.update-caches }}
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Setup build environment
        shell: bash
        run: |
          echo "VCVARSALL=$(vswhere -products \* -latest -property installationPath)\\VC\\Auxiliary\\Build\\vcvarsall.bat" >> $GITHUB_ENV
      - name: Configure and build
        run: scripts/build-windows-x64.cmd
        shell: cmd
        working-directory: ${{ github.workspace }}
        env:
          CFLAGS: "/UNDEBUG"
          CXXFLAGS: "/UNDEBUG"
      - name: Download Intel SDE using curl
        run: |
          curl -L -o sde-external-9.44.0-2024-08-22-win.tar.xz https://downloadmirror.intel.com/831748/sde-external-9.44.0-2024-08-22-win.tar.xz
      - name: Extract Intel SDE
        shell: bash
        run: |
          tar -xf sde-external-9.44.0-2024-08-22-win.tar.xz
      - name: Run tests using Intel SDE Arrow_Lake Processor
        if: ${{ inputs.run-tests }}
        run: |
          ${{ github.workspace }}\sde-external-9.44.0-2024-08-22-win\sde.exe -arl -- ctest -C Release --parallel $Env:NUMBER_OF_PROCESSORS
        working-directory: ${{ github.workspace }}/build/windows/x64

  build-and-test-sde-lnl:
    runs-on: windows-latest
    if: ${{ inputs.sde-processor == 'Lunar_Lake' || inputs.sde-processor == 'ALL' }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}
          max-size: "500M"
          save: ${{ inputs.update-caches }}
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Setup build environment
        shell: bash
        run: |
          echo "VCVARSALL=$(vswhere -products \* -latest -property installationPath)\\VC\\Auxiliary\\Build\\vcvarsall.bat" >> $GITHUB_ENV
      - name: Configure and build
        run: scripts/build-windows-x64.cmd
        shell: cmd
        working-directory: ${{ github.workspace }}
        env:
          CFLAGS: "/UNDEBUG"
          CXXFLAGS: "/UNDEBUG"
      - name: Download Intel SDE using curl
        run: |
          curl -L -o sde-external-9.44.0-2024-08-22-win.tar.xz https://downloadmirror.intel.com/831748/sde-external-9.44.0-2024-08-22-win.tar.xz
      - name: Extract Intel SDE
        shell: bash
        run: |
          tar -xf sde-external-9.44.0-2024-08-22-win.tar.xz
      - name: Run tests using Intel SDE Lunar_Lake Processor
        if: ${{ inputs.run-tests }}
        run: |
          ${{ github.workspace }}\sde-external-9.44.0-2024-08-22-win\sde.exe -lnl -- ctest -C Release --parallel $Env:NUMBER_OF_PROCESSORS
        working-directory: ${{ github.workspace }}/build/windows/x64
