name: Execute Windows x64 Tests with Intel SDE

env:
  SDE_URL: https://downloadmirror.intel.com/831748/sde-external-9.44.0-2024-08-22-win.tar.xz
  SDE_FILENAME: sde-external-9.44.0-2024-08-22-win.tar.xz

on:      
  workflow_dispatch:
    inputs:
      sde-processor:
        description: "Pick a SDE CPU Processor to run tests"
        required: true
        type: choice
        default: "ALL"
        options:
          - ALL
          - Skylake 
          - Cannon Lake 
          - Ice Lake 
          - SkyLake server 
          - Cascade Lake 
          - Cooper Lake 
          - Ice Lake server
          - Tiger Lake 
          - Alder Lake 
          - Meteor Lake 
          - Raptor Lake 
          - Sapphire Rapids 
          - Emerald Rapids 
          - Granite Rapids
          - Sierra Forest 
          - Arrow Lake 
          - Lunar Lake 

jobs:
  build:
    uses: ./.github/workflows/build-windows.yml

  test-sde:
    needs: build
    runs-on: windows-latest
    timeout-minutes: 60
    strategy:
      matrix:
        sde-processor: 
          - Skylake 
          - Cannon Lake 
          - Ice Lake 
          - SkyLake server 
          - Cascade Lake 
          - Cooper Lake 
          - Ice Lake server
          - Tiger Lake 
          - Alder Lake 
          - Meteor Lake 
          - Raptor Lake 
          - Sapphire Rapids 
          - Emerald Rapids 
          - Granite Rapids
          - Sierra Forest 
          - Arrow Lake 
          - Lunar Lake 

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-x64
          path: build/windows/x64/
          
      - name: Download Intel SDE using curl
        run: |
          curl -L -o ${{ env.SDE_FILENAME }} ${{ env.SDE_URL }}
          
      - name: Extract Intel SDE
        shell: bash
        run: |
          tar -xf ${{ env.SDE_FILENAME }}
      
      - name: Run tests using Intel SDE
        if: ${{ inputs.sde-processor == 'ALL' || inputs.sde-processor == matrix.sde-processor }}
        run: |
          SDE_PATH="${{ github.workspace }}\sde-external-9.44.0-2024-08-22-win\sde.exe"
          SDE_OPTION=""

          case "${{ matrix.sde-processor }}" in
            "Skylake")
              SDE_OPTION="-skl"
              ;;
            "Cannon Lake")
              SDE_OPTION="-cnl"
              ;;
            "Ice Lake")
              SDE_OPTION="-icl"
              ;;
            "SkyLake server")
              SDE_OPTION="-skx"
              ;;
            "Cascade Lake")
              SDE_OPTION="-clx"
              ;;
            "Cooper Lake")
              SDE_OPTION="-cpx"
              ;;
            "Ice Lake server")
              SDE_OPTION="-icx"
              ;;
            "Tiger Lake")
              SDE_OPTION="-tgl"
              ;;
            "Alder Lake")
              SDE_OPTION="-adl"
              ;;
            "Meteor Lake")
              SDE_OPTION="-mtl"
              ;;
            "Raptor Lake")
              SDE_OPTION="-rpl"
              ;;
            "Sapphire Rapids")
              SDE_OPTION="-spr"
              ;;
            "Emerald Rapids")
              SDE_OPTION="-emr"
              ;;
            "Granite Rapids")
              SDE_OPTION="-gnr"
              ;;
            "Sierra Forest")
              SDE_OPTION="-srf"
              ;;
            "Arrow Lake")
              SDE_OPTION="-arl"
              ;;
            "Lunar Lake")
              SDE_OPTION="-lnl"
              ;;
            *)
              echo "No matching processor specified."
              exit 1
              ;;
          esac
          
          $SDE_PATH $SDE_OPTION -- ctest -C Release --parallel $Env:NUMBER_OF_PROCESSORS
        working-directory: ${{ github.workspace }}/build/windows/x64
