name: Execute Windows x64 Tests with Intel SDE

env:
  SDE_URL: https://downloadmirror.intel.com/831748/sde-external-9.44.0-2024-08-22-win.tar.xz
  SDE_FILENAME: sde-external-9.44.0-2024-08-22-win.tar.xz
  SDE_PATH: ${{ github.workspace }}\sde-external-9.44.0-2024-08-22-win\sde.exe

on:      
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-windows.yml

  test-sde:
    runs-on: windows-latest
    needs: build
    timeout-minutes: 60
    continue-on-error: true
    strategy:
      matrix:
        sde-processor: [-skl, -cnl, -icl, -skx, -clx, -cpx, -icx, -tgl, -adl, -mtl, -rpl, -spr, -emr, -gnr, -srf, -arl, -lnl]

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-x64
          path: build/windows/x64/
          
      - name: Download Intel SDE using curl
        run: |
          curl -L -o ${{ env.SDE_FILENAME }} ${{ env.SDE_URL }}
          
      - name: Extract Intel SDE
        run: |
          tar -xf ${{ env.SDE_FILENAME }}
        shell: bash
      
      - name: NUMBER_OF_PROCESSORS
        run: echo $NUMBER_OF_PROCESSORS

      - name: env NUMBER_OF_PROCESSORS
        run: echo $Env:NUMBER_OF_PROCESSORS

      - name: Run tests using Intel SDE
        run: |
          ${{ env.SDE_PATH }} ${{ matrix.sde-processor }} -- ctest -C Release --parallel $NUMBER_OF_PROCESSORS
        working-directory: ${{ github.workspace }}/build/windows/x64
